#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
cd "$SCRIPT_DIR/.."

set -o errexit

echo "*** Updating submodules..."
git submodule sync --quiet
git submodule update --init
git submodule foreach --recursive --quiet "git submodule sync --quiet && git submodule update --init"

installed=`brew list`
deps="libssh2 libtool autoconf automake"

for lib in $deps
do
    # Skip packages that are already installed.
    echo "$installed" | grep -q "$lib" && code=$? || code=$?
    if [ "$code" -eq "0" ]
    then
        continue
    elif [ "$code" -ne "1" ]
    then
        exit $code
    fi

    echo "*** Installing $lib with Homebrew..."
    brew install "$lib"
done

brew_prefix=`brew --prefix`
expected_prefix=/usr/local
if [ "$brew_prefix" != "$expected_prefix" ]
then
    echo "*** Adding soft links into $expected_prefix..."

    products=(lib/libssh2.a include/libssh2.h include/libssh2_sftp.h include/libssh2_publickey.h)

    for product in "${products[@]}"
    do
        destination="$expected_prefix/$product"
        if [ -e "$destination" ]
        then
            continue
        fi

        sudo mkdir -p "$(dirname "$destination")"
        sudo ln -s "$brew_prefix/$product" "$destination"
    done
fi
