#!/bin/sh

set -e

# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="/usr/local/bin:$PATH"

cd "External/libgit2"

if [ -d "build" ]; then
    rm -rf "build"
fi

mkdir build
cd build

# OpenSSL is keg-only, so add its pkgconfig location manually
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

cmake -DBUILD_SHARED_LIBS:BOOL=OFF \
    -DLIBSSH2_INCLUDE_DIRS:PATH=/usr/local/include/ \
    -DBUILD_CLAR:BOOL=OFF \
    -DTHREADSAFE:BOOL=ON \
    ..
cmake --build .

product="libgit2.a"
install_path="../../${product}"
rm -rf $install_path
cp -v "${product}" "${install_path}"

echo "libgit2 has been updated."
