#!/bin/sh -ex

#
# script/update_libgit2
# ObjectiveGit
#
# Builds libgit2 static library for OS X platform.
# Script is now obsolete as the git2 project builds libgit2 as a dynamic framework,
# but is left here for reference.
#

# augment path to help it find cmake installed in /usr/local/bin,
# e.g. via brew. Xcode's Run Script phase doesn't seem to honor
# ~/.MacOSX/environment.plist
PATH="/usr/local/bin:$PATH"

if [ "External/libgit2.a" -nt "External/libgit2" ]
then
    echo "No update needed."
    exit 0
fi

cd "External/libgit2"

if [ -d "build" ]; then
    rm -rf "build"
fi

mkdir build
cd build

cmake -DBUILD_SHARED_LIBS:BOOL=OFF \
	-DLIBSSH2_INCLUDE_DIRS:PATH=/usr/local/include/ \
	-DBUILD_CLAR:BOOL=OFF \
	-DTHREADSAFE:BOOL=ON \
	..
cmake --build .

product="libgit2.a"
install_path="../../${product}"
if [ "${product}" -nt "${install_path}" ]; then
    cp -v "${product}" "${install_path}"
fi

echo "libgit2 has been updated."
